#!/bin/sh

mkdir styles
mkdir scripts
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>NewForce</title>
        <link rel="stylesheet" href="./styles/main.css">
    </head>

    <body>
        <main id="container">

        </main>

        <script type="module" src="./scripts/main.js"></script>
    </body>
</html>' >> index.html

    echo '@import url("https://fonts.googleapis.com/css?family=Comfortaa|Patua+One");

/*Typography
--------------------------------------------------------------*/
body,
button,
input,
select,
textarea {
	color: #404040;
	font-family: "Comfortaa", Arial, sans-serif;
	font-size: 14px;
	line-height: 1.5;
}

h1,h2,h3,h4,h5,h6 {
  font-family: "Patua One", serif;
  letter-spacing: 2px;
}' >> styles/main.css

echo 'console.log("Welcome to the main module")' >> scripts/main.js
